package at.yrs4j.yrslib;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libyrs.h:289</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsAfterTransactionEvent extends Structure {
	/**
	 * Descriptor of a document state at the moment of creating the transaction.<br>
	 * C type : YrsStateVector
	 */
	public YrsStateVector before_state;
	/**
	 * Descriptor of a document state at the moment of committing the transaction.<br>
	 * C type : YrsStateVector
	 */
	public YrsStateVector after_state;
	/**
	 * Information about all items deleted within the scope of a transaction.<br>
	 * C type : YrsDeleteSet
	 */
	public YrsDeleteSet delete_set;
	public YrsAfterTransactionEvent() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("before_state", "after_state", "delete_set");
	}
	/**
	 * @param before_state Descriptor of a document state at the moment of creating the transaction.<br>
	 * C type : YrsStateVector<br>
	 * @param after_state Descriptor of a document state at the moment of committing the transaction.<br>
	 * C type : YrsStateVector<br>
	 * @param delete_set Information about all items deleted within the scope of a transaction.<br>
	 * C type : YrsDeleteSet
	 */
	public YrsAfterTransactionEvent(YrsStateVector before_state, YrsStateVector after_state, YrsDeleteSet delete_set) {
		super();
		this.before_state = before_state;
		this.after_state = after_state;
		this.delete_set = delete_set;
	}
	public static class ByReference extends YrsAfterTransactionEvent implements Structure.ByReference {
		
	}

	public static class ByValue extends YrsAfterTransactionEvent implements Structure.ByValue {
		
	}
}
