package at.yrs4j.yrslib;
import com.sun.jna.Union;
/**
 * <i>native declaration : libyrs.h:451</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsEventContent extends Union {
	/** C type : YrsTextEvent */
	public YrsTextEvent text;
	/** C type : YrsMapEvent */
	public YrsMapEvent map;
	/** C type : YrsArrayEvent */
	public YrsArrayEvent array;
	/** C type : YrsXmlEvent */
	public YrsXmlEvent xml_elem;
	/** C type : YrsXmlTextEvent */
	public YrsXmlTextEvent xml_text;
	/** C type : YrsWeakLinkEvent */
	public YrsWeakLinkEvent weak;
	public YrsEventContent() {
		super();
	}
	/** @param map C type : YrsMapEvent */
	public YrsEventContent(YrsMapEvent map) {
		super();
		this.map = map;
		setType(YrsMapEvent.class);
	}
	/** @param array C type : YrsArrayEvent */
	public YrsEventContent(YrsArrayEvent array) {
		super();
		this.array = array;
		setType(YrsArrayEvent.class);
	}
	/** @param xml_elem C type : YrsXmlEvent */
	public YrsEventContent(YrsXmlEvent xml_elem) {
		super();
		this.xml_elem = xml_elem;
		setType(YrsXmlEvent.class);
	}
	/** @param text C type : YrsTextEvent */
	public YrsEventContent(YrsTextEvent text) {
		super();
		this.text = text;
		setType(YrsTextEvent.class);
	}
	/** @param weak C type : YrsWeakLinkEvent */
	public YrsEventContent(YrsWeakLinkEvent weak) {
		super();
		this.weak = weak;
		setType(YrsWeakLinkEvent.class);
	}
	/** @param xml_text C type : YrsXmlTextEvent */
	public YrsEventContent(YrsXmlTextEvent xml_text) {
		super();
		this.xml_text = xml_text;
		setType(YrsXmlTextEvent.class);
	}
	public static class ByReference extends YrsEventContent implements com.sun.jna.Structure.ByReference {
		
	}

	public static class ByValue extends YrsEventContent implements com.sun.jna.Structure.ByValue {
		
	}
}
