package at.yrs4j.yrslib;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libyrs.h:242</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsIdRange extends Structure {
	public int start;
	public int end;
	public YrsIdRange() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("start", "end");
	}
	public YrsIdRange(int start, int end) {
		super();
		this.start = start;
		this.end = end;
	}
	public static class ByReference extends YrsIdRange implements Structure.ByReference {
		
	}

	public static class ByValue extends YrsIdRange implements Structure.ByValue {
		
	}
}
