package at.yrs4j.yrslib;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : libyrs.h:335</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsInputContent extends Union {
	public byte flag;
	public double num;
	public long integer;
	/** C type : char* */
	public Pointer str;
	/** C type : char* */
	public Pointer buf;
	/** C type : YrsInput* */
	public YrsInput.ByReference values;
	/** C type : YrsMapInputData */
	public YrsMapInputData map;
	/** C type : YrsDoc* */
	public YrsDoc.ByReference doc;
	/** C type : const Weak* */
	public YrsLinkSource.ByReference weak;
	public YrsInputContent() {
		super();
	}
	/** @param map C type : YrsMapInputData */
	public YrsInputContent(YrsMapInputData map) {
		super();
		this.map = map;
		setType(YrsMapInputData.class);
	}
	public YrsInputContent(byte flag) {
		super();
		this.flag = flag;
		setType(Byte.TYPE);
	}
	public YrsInputContent(double num) {
		super();
		this.num = num;
		setType(Double.TYPE);
	}
	/** @param values C type : YrsInput* */
	public YrsInputContent(YrsInput.ByReference values) {
		super();
		this.values = values;
		setType(YrsInput.ByReference.class);
	}
	/** @param weak C type : const Weak* */
	public YrsInputContent(YrsLinkSource.ByReference weak) {
		super();
		this.weak = weak;
		setType(YrsLinkSource.ByReference.class);
	}
	/** @param str_or_buf C type : char*, or C type : char* */
	public YrsInputContent(Pointer str_or_buf) {
		super();
		this.buf = this.str = str_or_buf;
		setType(Pointer.class);
	}
	/** @param doc C type : YrsDoc* */
	public YrsInputContent(YrsDoc.ByReference doc) {
		super();
		this.doc = doc;
		setType(YrsDoc.ByReference.class);
	}
	public YrsInputContent(long integer) {
		super();
		this.integer = integer;
		setType(Long.TYPE);
	}
	public static class ByReference extends YrsInputContent implements com.sun.jna.Structure.ByReference {
		
	}

	public static class ByValue extends YrsInputContent implements com.sun.jna.Structure.ByValue {
		
	}
}
