package at.yrs4j.yrslib;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libyrs.h:323</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsMapInputData extends Structure {
	/** C type : char** */
	public PointerByReference keys;
	/** C type : YrsInput* */
	public YrsInput.ByReference values;
	public YrsMapInputData() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("keys", "values");
	}
	/**
	 * @param keys C type : char**<br>
	 * @param values C type : YrsInput*
	 */
	public YrsMapInputData(PointerByReference keys, YrsInput.ByReference values) {
		super();
		this.keys = keys;
		this.values = values;
	}
	public static class ByReference extends YrsMapInputData implements Structure.ByReference {
		
	}

    public static class ByValue extends YrsMapInputData implements Structure.ByValue {
		
	}
}
