package at.yrs4j.yrslib;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : libyrs.h:150</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsOutputContent extends Union {
	public byte flag;
	public double num;
	public long integer;
	/** C type : char* */
	public Pointer str;
	/** C type : const char* */
	public Pointer buf;
	/** C type : YrsOutput* */
	public YrsOutput.ByReference array;
	/** C type : YrsMapEntry* */
	public YrsMapEntry.ByReference map;
	/** C type : YrsBranch* */
	public YrsBranch.ByReference y_type;
	/** C type : YrsDoc* */
	public YrsDoc.ByReference y_doc;
	public YrsOutputContent() {
		super();
	}
	/** @param y_type C type : YrsBranch* */
	public YrsOutputContent(YrsBranch.ByReference y_type) {
		super();
		this.y_type = y_type;
		setType(YrsBranch.ByReference.class);
	}
	public YrsOutputContent(byte flag) {
		super();
		this.flag = flag;
		setType(Byte.TYPE);
	}
	public YrsOutputContent(double num) {
		super();
		this.num = num;
		setType(Double.TYPE);
	}
	/** @param map C type : YrsMapEntry* */
	public YrsOutputContent(YrsMapEntry.ByReference map) {
		super();
		this.map = map;
		setType(YrsMapEntry.ByReference.class);
	}
	/** @param str_or_buf C type : char*, or C type : const char* */
	public YrsOutputContent(Pointer str_or_buf) {
		super();
		this.buf = this.str = str_or_buf;
		setType(Pointer.class);
	}
	/** @param y_doc C type : YrsDoc* */
	public YrsOutputContent(YrsDoc.ByReference y_doc) {
		super();
		this.y_doc = y_doc;
		setType(YrsDoc.ByReference.class);
	}
	public YrsOutputContent(long integer) {
		super();
		this.integer = integer;
		setType(Long.TYPE);
	}
	/** @param array C type : YrsOutput* */
	public YrsOutputContent(YrsOutput.ByReference array) {
		super();
		this.array = array;
		setType(YrsOutput.ByReference.class);
	}
	public static class ByReference extends YrsOutputContent implements com.sun.jna.Structure.ByReference {
		
	}

    public static class ByValue extends YrsOutputContent implements com.sun.jna.Structure.ByValue {
		
	}
}
