package at.yrs4j.yrslib;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : libyrs.h:119</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsOptions extends Structure {
    /**
     * Globally unique 53-bit integer assigned to corresponding document replica as its identifier.
     * <br>
     * <br>
     * If two clients share the same `id` and will perform any updates, it will result in
     * <br>
     * unrecoverable document state corruption. The same thing may happen if the client restored
     * <br>
     * document state from snapshot, that didn't contain all of that clients updates that were sent
     * <br>
     * to other peers.
     */
    public long id;
    /**
     * A NULL-able globally unique Uuid v4 compatible null-terminated string identifier
     * <br>
     * of this document. If passed as NULL, a random Uuid will be generated instead.<br>
     * C type : const char*
     */
    public Pointer guid;
    /**
     * A NULL-able, UTF-8 encoded, null-terminated string of a collection that this document
     * <br>
     * belongs to. It's used only by providers.<br>
     * C type : const char*
     */
    public Pointer collection_id;

    /**
     * Encoding used by text editing operations on this document. It's used to compute
     * <br>
     * `YText`/`YXmlText` insertion offsets and text lengths. Either:
     * <br>
     * <br>
     * - `Y_OFFSET_BYTES`
     * <br>
     * - `Y_OFFSET_UTF16`
     */
    public byte encoding;
    /**
     * Boolean flag used to determine if deleted blocks should be garbage collected or not
     * <br>
     * during the transaction commits. Setting this value to 0 means GC will be performed.
     */
    public byte skip_gc;
    /**
     * Boolean flag used to determine if subdocument should be loaded automatically.
     * <br>
     * If this is a subdocument, remote peers will load the document as well automatically.
     */
    public byte auto_load;
    /**
     * Boolean flag used to determine whether the document should be synced by the provider now.
     */
    public byte should_load;

    public YrsOptions() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("id", "guid", "collection_id", "encoding", "skip_gc", "auto_load", "should_load");
    }

    /**
     * @param id            Globally unique 53-bit integer assigned to corresponding document replica as its identifier.
     *                      <br>
     *                      <br>
     *                      If two clients share the same `id` and will perform any updates, it will result in
     *                      <br>
     *                      unrecoverable document state corruption. The same thing may happen if the client restored
     *                      <br>
     *                      document state from snapshot, that didn't contain all of that clients updates that were sent
     *                      <br>
     *                      to other peers.<br>
     * @param guid          A NULL-able globally unique Uuid v4 compatible null-terminated string identifier
     *                      <br>
     *                      of this document. If passed as NULL, a random Uuid will be generated instead.<br>
     *                      C type : const char*<br>
     * @param collection_id A NULL-able, UTF-8 encoded, null-terminated string of a collection that this document
     *                      <br>
     *                      belongs to. It's used only by providers.<br>
     *                      C type : const char*<br>
     * @param encoding      Encoding used by text editing operations on this document. It's used to compute
     *                      <br>
     *                      `YText`/`YXmlText` insertion offsets and text lengths. Either:
     *                      <br>
     *                      <br>
     *                      - `Y_OFFSET_BYTES`
     *                      <br>
     *                      - `Y_OFFSET_UTF16`<br>
     * @param skip_gc       Boolean flag used to determine if deleted blocks should be garbage collected or not
     *                      <br>
     *                      during the transaction commits. Setting this value to 0 means GC will be performed.<br>
     * @param auto_load     Boolean flag used to determine if subdocument should be loaded automatically.
     *                      <br>
     *                      If this is a subdocument, remote peers will load the document as well automatically.<br>
     * @param should_load   Boolean flag used to determine whether the document should be synced by the provider now.
     */
    public YrsOptions(long id, Pointer guid, Pointer collection_id, byte encoding, byte skip_gc, byte auto_load, byte should_load) {
        super();
        this.id = id;
        this.guid = guid;
        this.collection_id = collection_id;
        this.encoding = encoding;
        this.skip_gc = skip_gc;
        this.auto_load = auto_load;
        this.should_load = should_load;
    }

    public static class ByReference extends YrsOptions implements Structure.ByReference {

    }

    public static class ByValue extends YrsOptions implements Structure.ByValue {

    }


}
