package at.yrs4j.yrslib;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : libyrs.h:472</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsPathSegmentCase extends Union {
	/** C type : const char* */
	public Pointer key;
	public int index;
	public YrsPathSegmentCase() {
		super();
	}
	/** @param key C type : const char* */
	public YrsPathSegmentCase(Pointer key) {
		super();
		this.key = key;
		setType(Pointer.class);
	}
	public YrsPathSegmentCase(int index) {
		super();
		this.index = index;
		setType(Integer.TYPE);
	}
	public static class ByReference extends YrsPathSegmentCase implements com.sun.jna.Structure.ByReference {
		
	}

	public static class ByValue extends YrsPathSegmentCase implements com.sun.jna.Structure.ByValue {
		
	}
}
