package at.yrs4j.yrslib;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libyrs.h:297</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsSubdocsEvent extends Structure {
	public int added_len;
	public int removed_len;
	public int loaded_len;
	/** C type : YrsDoc** */
	public YrsDoc.ByReference[] added;
	/** C type : YrsDoc** */
	public YrsDoc.ByReference[] removed;
	/** C type : YrsDoc** */
	public YrsDoc.ByReference[] loaded;
	public YrsSubdocsEvent() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("added_len", "removed_len", "loaded_len", "added", "removed", "loaded");
	}
	/**
	 * @param added C type : YrsDoc**<br>
	 * @param removed C type : YrsDoc**<br>
	 * @param loaded C type : YrsDoc**
	 */
	public YrsSubdocsEvent(int added_len, int removed_len, int loaded_len, YrsDoc.ByReference[] added, YrsDoc.ByReference[] removed, YrsDoc.ByReference[] loaded) {
		super();
		this.added_len = added_len;
		this.removed_len = removed_len;
		this.loaded_len = loaded_len;
		if ((added.length != this.added.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.added = added;
		if ((removed.length != this.removed.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.removed = removed;
		if ((loaded.length != this.loaded.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.loaded = loaded;
	}
	public static class ByReference extends YrsSubdocsEvent implements Structure.ByReference {
		
	}

	public static class ByValue extends YrsSubdocsEvent implements Structure.ByValue {
		
	}
}
