package at.yrs4j.yrslib;

import com.sun.jna.Structure;

import java.util.List;
/**
 * <i>native declaration : libyrs.h:634</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsUndoManagerOptions extends Structure {
	public int capture_timeout_millis;
	public YrsUndoManagerOptions() {
		super();
	}
	protected List<String> getFieldOrder() {
		return List.of("capture_timeout_millis");
	}
	public YrsUndoManagerOptions(int capture_timeout_millis) {
		super();
		this.capture_timeout_millis = capture_timeout_millis;
	}
	public static class ByReference extends YrsUndoManagerOptions implements Structure.ByReference {
		
	}

	public static class ByValue extends YrsUndoManagerOptions implements Structure.ByValue {
		
	}
}
