package at.yrs4j.yrslib;
import com.sun.jna.Structure;

import java.util.Collections;
import java.util.List;
/**
 * <i>native declaration : libyrs.h:61</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsXmlTreeWalker extends Structure {
	public YrsXmlTreeWalker() {
		super();
	}
	public byte dummy; // Dummy byte to ensure structure has non-zero size

	@Override
	protected List<String> getFieldOrder() {
		return Collections.singletonList("dummy");
	}

	public static class ByReference extends YrsXmlTreeWalker implements Structure.ByReference {
		
	}

	public static class ByValue extends YrsXmlTreeWalker implements Structure.ByValue {
		
	}
}
