package at.yrs4j.yrslib;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libyrs.h:212</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YrsXmlAttr extends Structure {
	/** C type : const char* */
	public Pointer name;
	/** C type : const char* */
	public Pointer value;
	public YrsXmlAttr() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("name", "value");
	}
	/**
	 * @param name C type : const char*<br>
	 * @param value C type : const char*
	 */
	public YrsXmlAttr(Pointer name, Pointer value) {
		super();
		this.name = name;
		this.value = value;
	}
	public static class ByReference extends YrsXmlAttr implements Structure.ByReference {
		
	}

	public static class ByValue extends YrsXmlAttr implements Structure.ByValue {
		
	}
}
